export interface Perfume {
  id: number;
  marca: string;
  nombre: string;
  imagen: string;
  precio: number;
  notas: {
    salida: string[];
    corazon: string[];
    fondo: string[];
  };
  genero: string;
  fragancia_referencia: string;
  descripcion: string;
  rating: number;
  sinDescuento?: boolean;
  quantity?: number;
  sellado?: boolean;
  esRegalo?: boolean;
  esNuevo?: boolean;
}

export const perfumes: Perfume[] = [
  {
    id: 160,
    marca: "Lattafa Perfumes",
    nombre: "Lattafa Kit Badee Al Oud Collection",
    imagen: "https://i.imgur.com/km9xO6J.png",
    precio: 82000,
    notas: {
      salida: ["Azafrán", "Nuez moscada"],
      corazon: ["Oud", "Pachulí"],
      fondo: ["Almizcle", "Pachulí"],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Exclusivo set de miniaturas de la línea Badee Al Oud. Ideal para descubrir fragancias lujosas y potentes.",
    rating: 4.9,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 161,
    marca: "Lattafa Perfumes",
    nombre: "Lattafa Kit Mini Yara Collection",
    imagen: "https://i.imgur.com/nQnokyJ.png",
    precio: 50000,
    notas: {
      salida: ["Orquídea", "Heliotropo"],
      corazon: ["Acorde Gourmand", "Frutas tropicales"],
      fondo: ["Vainilla", "Almizcle"],
    },
    genero: "Mujer",
    fragancia_referencia: "",
    descripcion: "Colección de las virales fragancias Yara en formato miniatura. Dulces, femeninas y encantadoras.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 162,
    marca: "Maison Alhambra",
    nombre: "Yeah Man Parfum 100ml",
    imagen: "https://i.imgur.com/6WpYbv0.png",
    precio: 36000,
    notas: {
      salida: ["Manzana", "Jengibre", "Bergamota"],
      corazon: ["Salvia", "Enebro", "Geranio"],
      fondo: ["Ámbar", "Haba tonka", "Cedro"],
    },
    genero: "Hombre",
    fragancia_referencia: "Y Eau de Parfum de YSL",
    descripcion: "Una fragancia fresca y poderosa que proyecta confianza y modernidad.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 163,
    marca: "Lattafa Perfumes",
    nombre: "Lattafa Atlas EDP 55ml",
    imagen: "https://i.imgur.com/JS937S7.png",
    precio: 58000,
    notas: {
      salida: ["Agua de mar", "Sal", "Algas"],
      corazon: ["Calone", "Hedione"],
      fondo: ["Almizcle", "Ámbar", "Cedro"],
    },
    genero: "Unisex",
    fragancia_referencia: "Megamare de Orto Parisi",
    descripcion: "Una fragancia marina profunda y eterna, con una proyección y duración extraordinarias.",
    rating: 4.9,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 164,
    marca: "Lattafa Perfumes",
    nombre: "Lattafa Khamrah (Black) EDP 100ml",
    imagen: "https://i.imgur.com/bl2WvMv.png",
    precio: 50000,
    notas: {
      salida: ["Canela", "Cardamomo", "Jengibre"],
      corazon: ["Praliné", "Frutas confitadas", "Café"],
      fondo: ["Vainilla", "Haba tonka", "Benjuí"],
    },
    genero: "Unisex",
    fragancia_referencia: "Khamrah Qahwa",
    descripcion: "La versión intensa con notas de café del aclamado Khamrah. Un aroma cálido, dulce y especiado.",
    rating: 4.9,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 165,
    marca: "Cacharel",
    nombre: "Amor Amor EDT 100ml",
    imagen: "https://i.imgur.com/qyGR2ty.png",
    precio: 70000,
    notas: {
      salida: ["Grosellas negras", "Naranja", "Pomelo"],
      corazon: ["Rosa", "Damasco", "Jazmín"],
      fondo: ["Vainilla", "Haba tonka", "Almizcle"],
    },
    genero: "Mujer",
    fragancia_referencia: "",
    descripcion: "El perfume del amor: floral, frutal y lleno de vida. Un clásico que nunca falla.",
    rating: 4.7,
    sinDescuento: false,
    sellado: true,
    esNuevo: true,
  },
  {
    id: 84,
    marca: "Tubbees",
    nombre: "Cookies & Cream 50ml EDP",
    imagen: "https://i.imgur.com/BvmtiJ5.png",
    precio: 27000,
    notas: {
      salida: ["Mantequilla", "azúcar"],
      corazon: ["Leche", "chocolate con leche"],
      fondo: ["Vainilla", "almizcle blanco"],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Gourmand cremoso y adictivo, huele a postre recién hecho y momentos felices.",
    rating: 4.8,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 85,
    marca: "Tubbees",
    nombre: "Sweet Caramel 50ml EDP",
    imagen: "https://i.imgur.com/vwhDMd8.png",
    precio: 27000,
    notas: {
      salida: [],
      corazon: ["Vainilla", "leche"],
      fondo: ["Vainilla", "haba tonka"],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Cremosa y envolvente: caramelo derretido con vainilla cálida y leche suave.",
    rating: 4.7,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 87,
    marca: "Tubbees",
    nombre: "Bubble Gum 50ml EDP",
    imagen: "https://i.imgur.com/A1Ty93q.png",
    precio: 27000,
    notas: {
      salida: ["Frutas", "clavo de olor"],
      corazon: ["Goma de mascar", "aceite de naranja"],
      fondo: ["Vainilla", "pachulí", "cachemira"],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Chicloso, juguetón y adictivo con frescura cítrica y fondo avainillado.",
    rating: 4.6,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 120,
    marca: "Maison Alhambra",
    nombre: "Panther Pour Homme 30 ml",
    imagen: "https://i.imgur.com/5soLGLi.png",
    precio: 15000,
    notas: {
      salida: ["Limón de Amalfi", "Entusiasmo de limón", "lavanda"],
      corazon: ["Lavanda", "manzana", "humo", "notas terrosas", "pachulí"],
      fondo: ["Vainilla", "lavanda", "vetiver"],
    },
    genero: "Masculino",
    fragancia_referencia: "Phantom de Paco Rabanne",
    descripcion: "Una fragancia masculina de la familia olfativa Aromática. Ideal para hombres que buscan una esencia fresca y sofisticada, con un equilibrio entre notas cítricas, florales y amaderadas.",
    rating: 4.9,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 89,
    marca: "Maison Alhambra",
    nombre: "Dark Door Sport 100ml EDP",
    imagen: "https://i.imgur.com/ZGDNzNq.png",
    precio: 37000,
    notas: {
      salida: ["Pomelo", "limón", "resina de elemí", "bergamota"],
      corazon: ["Jengibre", "cedro", "vetiver"],
      fondo: ["Lavanda", "romero", "sándalo"],
    },
    genero: "Hombre",
    fragancia_referencia: "Dior Homme Sport",
    descripcion: "Fresca y energética; perfecta para el día, entrenar o climas cálidos.",
    rating: 4.6,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 91,
    marca: "Maison Alhambra",
    nombre: "Léonie Intense 30ml EDP",
    imagen: "https://i.imgur.com/C4ftYm2.png",
    precio: 15000,
    notas: {
      salida: ["Lavanda", "naranja tangerina", "grosellas negras", "petit grain"],
      corazon: ["Lavanda", "jazmín", "flor de azahar"],
      fondo: ["Vainilla de Madagascar", "ámbar", "cedro", "almizcle"],
    },
    genero: "Mujer",
    fragancia_referencia: "Libre Intense – YSL",
    descripcion: "Potente, elegante y sensual, con frescura floral y dulzura cremosa.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 95,
    marca: "Maison Alhambra",
    nombre: "Glacier Pour Homme 30ml EDP",
    imagen: "https://i.imgur.com/qZAhYu5.png",
    precio: 15000,
    notas: {
      salida: ["Lavanda", "menta", "cardamomo", "bergamota"],
      corazon: ["Canela", "flor de azahar del naranjo", "alcaravea"],
      fondo: ["Vainilla", "haba tonka", "sándalo", "ámbar"],
    },
    genero: "Hombre",
    fragancia_referencia: "Le Male – Jean Paul Gaultier",
    descripcion: "Frescura aromática con fondo dulce envolvente; magnético y moderno.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },
  
  {
    id: 108,
    marca: "Maison Alhambra",
    nombre: "CASSIUS EDP 30ml",
    imagen: "https://i.imgur.com/SFVy9jt.png",
    precio: 15000,
    notas: {
      salida: ["Heliotropo", "comino", "bergamota"],
      corazon: ["Almendra", "lavanda", "jazmín"],
      fondo: ["Vainilla", "ámbar", "sándalo"],
    },
    genero: "Hombre",
    fragancia_referencia: "Pegasus de Parfums De Marly",
    descripcion: "Intensa y envolvente, ideal para la noche, salidas especiales o estaciones frías.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },

  {
    id: 17,
    marca: "Perfumeros",
    nombre: "Perfumeros",
    imagen: "https://i.imgur.com/yMxitsz.png",
    precio: 3500,
    notas: {
      salida: [""],
      corazon: [""],
      fondo: [""],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Disfruta de llevar tus perfume favorito a todos lados",
    sinDescuento: true,
    rating: 4.2,
    sellado: true,
  },
  {
    id: 36,
    marca: "Britney Spears",
    nombre: "Fantasy 100ml EDP",
    imagen: "https://i.imgur.com/RMxS2Is.png",
    precio: 50000,
    notas: {
      salida: ["Kiwi", "lichi rojo", "membrillo"],
      corazon: ["Chocolate blanco", "quequito", "orquídea", "jazmín"],
      fondo: ["Almizcle", "raíz de lirio", "notas amaderadas"],
    },
    genero: "Mujer",
    fragancia_referencia: "",
    descripcion: "Una fragancia icónica, dulce y encantadora, que invita a soñar.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 37,
    marca: "Maison Alhambra",
    nombre: "Jorge di Profumo Aqua 100ml EDP",
    imagen: "https://i.imgur.com/U48EYDK.png",
    precio: 40000,
    notas: {
      salida: ["Bergamota", "limón siciliano", "pimienta negra"],
      corazon: ["Lavanda", "tabaco", "geranio"],
      fondo: ["Sándalo", "vetiver", "almizcle"],
    },
    genero: "Hombre",
    fragancia_referencia: "Acqua di Gio Profumo – Giorgio Armani",
    descripcion: "Un perfume intenso, moderno y sofisticado, pensado para el hombre que deja su marca.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },
  
  {
    id: 57,
    marca: "Maison Alhambra",
    nombre: "Narissa Rouge 100ml EDP",
    imagen: "https://i.imgur.com/EEWFvUp.png",
    precio: 40000,
    notas: {
      salida: ["Iris", "rosa de Bulgaria"],
      corazon: ["Almizcle", "nardos", "flor de azahar"],
      fondo: ["Haba tonka", "vainilla", "vetiver", "sándalo", "cedro"],
    },
    genero: "Mujer",
    fragancia_referencia: "Narciso Rouge de Narciso Rodriguez",
    descripcion: "Un perfume intenso, sensual y magnético.",
    rating: 4.8,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 59,
    marca: "Maison Alhambra",
    nombre: "Philos Opus Noir 100ml EDP",
    imagen: "https://i.imgur.com/v2v8Icy.png",
    precio: 34800,
    notas: {
      salida: ["Frutas", "rosa turca"],
      corazon: ["Ylang-ylang", "cuero", "nuez moscada", "ámbar"],
      fondo: ["Pachulí", "vainilla", "vetiver", "almizcle", "cedro"],
    },
    genero: "Unisex",
    fragancia_referencia: "Opera de Xerjoff",
    descripcion: "Una fragancia opulenta, artística y poderosa.",
    rating: 4.9,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 63,
    marca: "Maison Alhambra",
    nombre: "Opera Rouge 100ml EDP",
    imagen: "https://i.imgur.com/GmkcNdO.png",
    precio: 47000,
    notas: {
      salida: ["Pimienta rosa", "pera"],
      corazon: ["Jazmín", "café", "pimienta rosa"],
      fondo: ["Vainilla", "cedro", "pachulí"],
    },
    genero: "Mujer",
    fragancia_referencia: "Black Opium – YSL",
    descripcion: "Una fragancia oscura, vibrante y seductora.",
    rating: 4.8,
    sinDescuento: false,
    sellado: false,
  },
  {
    id: 71,
    marca: "Maison Alhambra",
    nombre: "Panther Pour Homme 100ml EDP",
    imagen: "https://i.imgur.com/pu3CaeR.png",
    precio: 40000,
    notas: {
      salida: ["Cítricos", "bergamota"],
      corazon: ["Especias", "lavanda"],
      fondo: ["Ámbar", "almizcle"],
    },
    genero: "Hombre",
    fragancia_referencia: "Phantom de Paco Rabanne",
    descripcion: "Una fragancia masculina poderosa y elegante.",
    rating: 4.7,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 149,
    marca: "Maison Alhambra",
    nombre: "Bad Femme 30 ml",
    imagen: "https://i.imgur.com/xIoHc4O.png",
    precio: 15000,
    notas: {
      salida: ["Almendra", "Café", "Limón", "Bergamota"],
      corazon: ["Nardos", "Jazmín Sambac", "Flor de Azahar"],
      fondo: ["Haba tonka", "Cacao", "Vainilla", "Praliné", "Sándalo"],
    },
    genero: "Femenino",
    fragancia_referencia: "Good Girl de Carolina Herrera",
    descripcion: "Una fragancia sensual y sofisticada que juega con la dualidad femenina.",
    rating: 4.8,
    sinDescuento: false,
    sellado: true,
  },
  {
    id: 83,
    marca: "Calvin Klein",
    nombre: "CK IN2U 100ml EDT",
    imagen: "https://i.imgur.com/WEIdKAP.png",
    precio: 58500,
    notas: {
      salida: ["Lima", "hojas de tomate", "bergamota"],
      corazon: ["Cacao", "orquídea", "especias"],
      fondo: ["Cedro", "ámbar", "vainilla"],
    },
    genero: "Unisex",
    fragancia_referencia: "",
    descripcion: "Una fragancia unisex moderna y juvenil, fresca y energética.",
    rating: 4.5,
    sinDescuento: false,
    sellado: true,
  },
];
